In [1]:
import pandas as pd

df = pd.read_csv("Indian_English_Dyslexia_Prototype_32Q.csv")

print("Shape:", df.shape)

print("\nTotal missing values:")
print(df.isnull().sum().sum())

print("\nColumns having missing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])
pd.set_option("display.max_columns", None)

display(df.head(5))

Shape: (1500, 197)

Total missing values:
0

Columns having missing values:
Series([], dtype: int64)

,Gender,Nativelang,Otherlang,Age,Clicks1,Hits1,Misses1,Score1,Accuracy1,Missrate1,Clicks2,Hits2,Misses2,Score2,Accuracy2,Missrate2,Clicks3,Hits3,Misses3,Score3,Accuracy3,Missrate3,Clicks4,Hits4,Misses4,Score4,Accuracy4,Missrate4,Clicks5,Hits5,Misses5,Score5,Accuracy5,Missrate5,Clicks6,Hits6,Misses6,Score6,Accuracy6,Missrate6,Clicks7,Hits7,Misses7,Score7,Accuracy7,Missrate7,Clicks8,Hits8,Misses8,Score8,Accuracy8,Missrate8,Clicks9,Hits9,Misses9,Score9,Accuracy9,Missrate9,Clicks10,Hits10,Misses10,Score10,Accuracy10,Missrate10,Clicks11,Hits11,Misses11,Score11,Accuracy11,Missrate11,Clicks12,Hits12,Misses12,Score12,Accuracy12,Missrate12,Clicks13,Hits13,Misses13,Score13,Accuracy13,Missrate13,Clicks14,Hits14,Misses14,Score14,Accuracy14,Missrate14,Clicks15,Hits15,Misses15,Score15,Accuracy15,Missrate15,Clicks16,Hits16,Misses16,Score16,Accuracy16,Missrate16,Clicks17,Hits17,Misses17,Score17,Accuracy17,Missrate17,Clicks18,Hits18,Misses18,Score18,Accuracy18,Missrate18,Clicks19,Hits19,Misses19,Score19,Accuracy19,Missrate19,Clicks20,Hits20,Misses20,Score20,Accuracy20,Missrate20,Clicks21,Hits21,Misses21,Score21,Accuracy21,Missrate21,Clicks22,Hits22,Misses22,Score22,Accuracy22,Missrate22,Clicks23,Hits23,Misses23,Score23,Accuracy23,Missrate23,Clicks24,Hits24,Misses24,Score24,Accuracy24,Missrate24,Clicks25,Hits25,Misses25,Score25,Accuracy25,Missrate25,Clicks26,Hits26,Misses26,Score26,Accuracy26,Missrate26,Clicks27,Hits27,Misses27,Score27,Accuracy27,Missrate27,Clicks28,Hits28,Misses28,Score28,Accuracy28,Missrate28,Clicks29,Hits29,Misses29,Score29,Accuracy29,Missrate29,Clicks30,Hits30,Misses30,Score30,Accuracy30,Missrate30,Clicks31,Hits31,Misses31,Score31,Accuracy31,Missrate31,Clicks32,Hits32,Misses32,Score32,Accuracy32,Missrate32,Dyslexia
0,Male,Malayalam,No,7,14,11,3,11,0.7857,0.2143,14,11,3,11,0.7857,0.2143,16,13,3,13,0.8125,0.1875,16,9,7,9,0.5625,0.4375,15,11,4,11,0.7333,0.2667,12,10,2,10,0.8333,0.1667,14,10,4,10,0.7143,0.2857,17,11,6,11,0.6471,0.3529,19,14,5,14,0.7368,0.2632,9,6,3,6,0.6667,0.3333,14,11,3,11,0.7857,0.2143,10,8,2,8,0.8000,0.2000,12,9,3,9,0.7500,0.2500,12,8,4,8,0.6667,0.3333,16,13,3,13,0.8125,0.1875,9,6,3,6,0.6667,0.3333,12,9,3,9,0.7500,0.2500,13,10,3,10,0.7692,0.2308,11,9,2,9,0.8182,0.1818,14,10,4,10,0.7143,0.2857,14,10,4,10,0.7143,0.2857,14,12,2,12,0.8571,0.1429,13,9,4,9,0.6923,0.3077,12,10,2,10,0.8333,0.1667,8,7,1,7,0.8750,0.1250,13,10,3,10,0.7692,0.2308,13,10,3,10,0.7692,0.2308,12,10,2,10,0.8333,0.1667,16,10,6,10,0.6250,0.3750,11,8,3,8,0.7273,0.2727,16,13,3,13,0.8125,0.1875,8,5,3,5,0.6250,0.3750,Yes
1,Female,Other,Yes,15,13,11,2,11,0.8462,0.1538,13,11,2,11,0.8462,0.1538,15,14,1,14,0.9333,0.0667,15,14,1,14,0.9333,0.0667,8,7,1,7,0.8750,0.1250,14,11,3,11,0.7857,0.2143,8,7,1,7,0.8750,0.1250,12,11,1,11,0.9167,0.0833,8,8,0,8,1.0000,0.0000,16,13,3,13,0.8125,0.1875,10,8,2,8,0.8000,0.2000,12,10,2,10,0.8333,0.1667,12,10,2,10,0.8333,0.1667,9,8,1,8,0.8889,0.1111,16,12,4,12,0.7500,0.2500,16,14,2,14,0.8750,0.1250,8,8,0,8,1.0000,0.0000,13,11,2,11,0.8462,0.1538,8,7,1,7,0.8750,0.1250,10,9,1,9,0.9000,0.1000,15,12,3,12,0.8000,0.2000,14,11,3,11,0.7857,0.2143,15,12,3,12,0.8000,0.2000,13,9,4,9,0.6923,0.3077,11,10,1,10,0.9091,0.0909,11,10,1,10,0.9091,0.0909,16,13,3,13,0.8125,0.1875,17,13,4,13,0.7647,0.2353,16,12,4,12,0.7500,0.2500,19,17,2,17,0.8947,0.1053,9,8,1,8,0.8889,0.1111,15,14,1,14,0.9333,0.0667,No
2,Female,Hindi,Yes,14,8,7,1,7,0.8750,0.1250,8,7,1,7,0.8750,0.1250,11,10,1,10,0.9091,0.0909,16,14,2,14,0.8750,0.1250,10,8,2,8,0.8000,0.2000,16,13,3,13,0.8125,0.1875,17,15,2,15,0.8824,0.1176,14,12,2,12,0.8571,0.1429,12,10,2,10,0.8333,0.1667,12,10,2,10,0.8333,0.1667,12,9,3,9,0.7500,0.2500,14,12,2,12,0.8571,0.1429,12,9,3,9,0.7500,0.2500,13,10,3,10,0.7692,0.2308,10,8,2,8,0.8000,0.2000,13,10,3,10,0.7692,0.2308,18,14,4,14,0.7778,0.2222,11,10,1,10,0.9091,0.0909,16,15,1,15,0.9375,0.0625,19,17,2,17,0.8947,0.1053,13,12,1,12,0.9231,0.0769,11,9,2,9,0.8182,0.1818,19,15,4,15,0.7895,0.2105,10,10,0,10,1.0000,0.0000,18,14,4,14,0.7778,0.2222,11,10,1,10,0.9091,0.0909,15,12,3,12,0.8000,0.2000,16,15,1,15,0.9375,0.0625,19,18,1,18,0.9474,0.0526,16,12,4,12,0.7500,0.2500,9,8,1,8,0.8889,0.1111,15,13,2,13,0.8667,0.1333,No
3,Female,Hindi,No,11,9,7,2,7,0.7778,0.2222,15,13,2,13,0.8667,0.1333,13,11,2,11,0.8462,0.1538,16,13,3,13,0.8125,0.1875,13,11,2,11,0.8462,0.1538,11,9,2,9,0.8182,0.1818,12,10,2,10,0.8333,0.1667,19,18,1,18,0.9474,0.0526,16,12,4,12,0.7500,0.2500,11,10,1,10,0.9091,0.0909,9,8,1,8,0.8889,0.1111,12,10,2,10,0.8333,0.1667,8,7,1,7,0.8750,0.1250,8,7,1,7,0.8750,0.1250,10,8,2,8,0.8000,0.2000,10,8,2,8,0.8000,0.2000,16,12,4,12,0.7500,0.2500,14,11,3,11,0.7857,0.2143,14,11,3,11,0.7857,0.2143,12,11,1,11,0.9167,0.0833,17,14,3,14,0.8235,0.1765,16,14,2,14,0.8750,0.1250,18,15,3,15,0.8333,0.1667,19,15,4,15,0.7895,0.2105,17,15,2,15,0.8824,0.1176,8,7,1,7,0.8750,0.1250,16,14,2,14,0.8750,0.1250,8,7,1,7,0.8750,0.1250,18,12,6,12,0.6667,0.3333,16,14,2,14,0.8750,0.1250,16,12,4,12,0.7500,0.2500,14,13,1,13,0.9286,0.0714,No
4,Male,Bengali,Yes,11,15,13,2,13,0.8667,0.1333,13,12,1,12,0.9231,0.0769,18,16,2,16,0.8889,0.1111,10,8,2,8,0.8000,0.2000,13,10,3,10,0.7692,0.2308,13,11,2,11,0.8462,0.1538,9,8,1,8,0.8889,0.1111,13,10,3,10,0.7692,0.2308,12,11,1,11,0.9167,0.0833,19,15,4,15,0.7895,0.2105,13,11,2,11,0.8462,0.1538,17,15,2,15,0.8824,0.1176,16,14,2,14,0.8750,0.1250,9,7,2,7,0.7778,0.2222,19,15,4,15,0.7895,0.2105,11,9,2,9,0.8182,0.1818,11,9,2,9,0.8182,0.1818,11,9,2,9,0.8182,0.1818,10,9,1,9,0.9000,0.1000,8,7,1,7,0.8750,0.1250,12,11,1,11,0.9167,0.0833,14,12,2,12,0.8571,0.1429,11,9,2,9,0.8182,0.1818,10,10,0,10,1.0000,0.0000,17,15,2,15,0.8824,0.1176,14,12,2,12,0.8571,0.1429,11,8,3,8,0.7273,0.2727,15,13,2,13,0.8667,0.1333,12,9,3,9,0.7500,0.2500,17,13,4,13,0.7647,0.2353,9,8,1,8,0.8889,0.1111,13,10,3,10,0.7692,0.2308,No

In [2]:
df[[
    "Clicks1",
    "Hits1",
    "Misses1",
    "Score1",
    "Accuracy1",
    "Missrate1"
]].head(10)

   Clicks1  Hits1  Misses1  Score1  Accuracy1  Missrate1
0       14     11        3      11     0.7857     0.2143
1       13     11        2      11     0.8462     0.1538
2        8      7        1       7     0.8750     0.1250
3        9      7        2       7     0.7778     0.2222
4       15     13        2      13     0.8667     0.1333
5       14     12        2      12     0.8571     0.1429
6       14     11        3      11     0.7857     0.2143
7        9      8        1       8     0.8889     0.1111
8       14     12        2      12     0.8571     0.1429
9        8      8        0       8     1.0000     0.0000

In [3]:
df[[
    "Clicks32",
    "Hits32",
    "Misses32",
    "Score32",
    "Accuracy32",
    "Missrate32"
]].head(10)

   Clicks32  Hits32  Misses32  Score32  Accuracy32  Missrate32
0         8       5         3        5      0.6250      0.3750
1        15      14         1       14      0.9333      0.0667
2        15      13         2       13      0.8667      0.1333
3        14      13         1       13      0.9286      0.0714
4        13      10         3       10      0.7692      0.2308
5        16      13         3       13      0.8125      0.1875
6        19      15         4       15      0.7895      0.2105
7        15      12         3       12      0.8000      0.2000
8        17      15         2       15      0.8824      0.1176
9         8       6         2        6      0.7500      0.2500

In [4]:
# Questions used for each age group

questions_7_8 = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    14, 15, 16, 17, 22, 23, 30
]

questions_9_11 = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    22, 23, 24, 26, 27, 28, 30
]

questions_12_17 = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28,
    30, 31, 32
]

print("7–8 questions:", len(questions_7_8))
print("9–11 questions:", len(questions_9_11))
print("12–17 questions:", len(questions_12_17))

7–8 questions: 19
9–11 questions: 27
12–17 questions: 31

In [5]:
measures = [
    "Clicks",
    "Hits",
    "Misses",
    "Score",
    "Accuracy",
    "Missrate"
]

def get_question_columns(question_list):
    columns = []
    
    for q in question_list:
        for measure in measures:
            columns.append(f"{measure}{q}")
    
    return columns
features_7_8 = get_question_columns(questions_7_8)
features_9_11 = get_question_columns(questions_9_11)
features_12_17 = get_question_columns(questions_12_17)

print("7–8 features:", len(features_7_8))
print("9–11 features:", len(features_9_11))
print("12–17 features:", len(features_12_17))

7–8 features: 114
9–11 features: 162
12–17 features: 186

In [6]:
demographic_features = [
    "Gender",
    "Nativelang",
    "Otherlang",
    "Age"
]

features_7_8 = demographic_features + features_7_8
features_9_11 = demographic_features + features_9_11
features_12_17 = demographic_features + features_12_17

print("7–8 total features:", len(features_7_8))
print("9–11 total features:", len(features_9_11))
print("12–17 total features:", len(features_12_17))

7–8 total features: 118
9–11 total features: 166
12–17 total features: 190

In [8]:
df_7_8 = df[(df["Age"] >= 7) & (df["Age"] <= 8)][
    features_7_8 + ["Dyslexia"]
]

df_9_11 = df[(df["Age"] >= 9) & (df["Age"] <= 11)][
    features_9_11 + ["Dyslexia"]
]

df_12_17 = df[(df["Age"] >= 12) & (df["Age"] <= 17)][
    features_12_17 + ["Dyslexia"]
]
print("7–8:", df_7_8.shape)
print("9–11:", df_9_11.shape)
print("12–17:", df_12_17.shape)

7–8: (286, 119)
9–11: (380, 167)
12–17: (834, 191)

In [9]:
X_7_8 = df_7_8.drop("Dyslexia", axis=1)
y_7_8 = df_7_8["Dyslexia"].map({
    "No": 0,
    "Yes": 1
})

print("X shape:", X_7_8.shape)
print("y shape:", y_7_8.shape)

print("\nTarget distribution:")
print(y_7_8.value_counts())

X shape: (286, 118)
y shape: (286,)

Target distribution:
Dyslexia
0    255
1     31
Name: count, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

X_train_7_8, X_test_7_8, y_train_7_8, y_test_7_8 = train_test_split(
    X_7_8,
    y_7_8,
    test_size=0.20,
    random_state=42,
    stratify=y_7_8
)

print("Training data:", X_train_7_8.shape)
print("Testing data:", X_test_7_8.shape)

Training data: (228, 118)
Testing data: (58, 118)

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier

In [12]:
categorical_features = [
    "Gender",
    "Nativelang",
    "Otherlang"
]

numerical_features = [
    col for col in X_7_8.columns
    if col not in categorical_features
]

preprocessor_7_8 = ColumnTransformer([
    (
        "categorical",
        OneHotEncoder(
            drop="first",
            handle_unknown="ignore"
        ),
        categorical_features
    ),
    (
        "numerical",
        "passthrough",
        numerical_features
    )
])

In [13]:
scale_pos_weight_7_8 = (
    (y_train_7_8 == 0).sum()
    / (y_train_7_8 == 1).sum()
)

print("Scale positive weight:", scale_pos_weight_7_8)

Scale positive weight: 8.12

In [14]:
xgb_7_8 = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight_7_8,
    random_state=42,
    eval_metric="logloss"
)
pipeline_7_8 = Pipeline([
    ("preprocessing", preprocessor_7_8),
    ("xgboost", xgb_7_8)
])

In [15]:
pipeline_7_8.fit(
    X_train_7_8,
    y_train_7_8
)

print("7–8 XGBoost model trained successfully!")

7–8 XGBoost model trained successfully!

In [16]:
# ============================================================
# 9–11 AND 12–17 AGE-SPECIFIC XGBOOST MODELS
# ============================================================

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

from xgboost import XGBClassifier


# ------------------------------------------------------------
# 1. QUESTION LISTS
# ------------------------------------------------------------

questions_9_11 = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    22, 23, 24, 26, 27, 28, 30
]

questions_12_17 = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28,
    30, 31, 32
]


# ------------------------------------------------------------
# 2. MEASURES FOR EACH QUESTION
# ------------------------------------------------------------

measures = [
    "Clicks",
    "Hits",
    "Misses",
    "Score",
    "Accuracy",
    "Missrate"
]


# ------------------------------------------------------------
# 3. FUNCTION TO CREATE QUESTION FEATURE NAMES
# ------------------------------------------------------------

def get_question_columns(question_list):

    columns = []

    for q in question_list:

        for measure in measures:

            columns.append(f"{measure}{q}")

    return columns


# ------------------------------------------------------------
# 4. DEMOGRAPHIC FEATURES
# ------------------------------------------------------------

demographic_features = [
    "Gender",
    "Nativelang",
    "Otherlang",
    "Age"
]


# ------------------------------------------------------------
# 5. CREATE FEATURES FOR 9–11
# ------------------------------------------------------------

features_9_11 = (
    demographic_features
    + get_question_columns(questions_9_11)
)


# ------------------------------------------------------------
# 6. CREATE FEATURES FOR 12–17
# ------------------------------------------------------------

features_12_17 = (
    demographic_features
    + get_question_columns(questions_12_17)
)


print("9–11 features:", len(features_9_11))
print("12–17 features:", len(features_12_17))


# ------------------------------------------------------------
# 7. CREATE AGE-SPECIFIC DATA
# ------------------------------------------------------------

df_9_11 = df[
    (df["Age"] >= 9) &
    (df["Age"] <= 11)
][features_9_11 + ["Dyslexia"]]


df_12_17 = df[
    (df["Age"] >= 12) &
    (df["Age"] <= 17)
][features_12_17 + ["Dyslexia"]]


print("\n9–11 dataset shape:", df_9_11.shape)
print("12–17 dataset shape:", df_12_17.shape)


# ============================================================
# MODEL 2 — AGE 9–11
# ============================================================

print("\n====================================")
print("TRAINING MODEL FOR AGE 9–11")
print("====================================")


# ------------------------------------------------------------
# 8. Separate X and y
# ------------------------------------------------------------

X_9_11 = df_9_11.drop("Dyslexia", axis=1)

y_9_11 = df_9_11["Dyslexia"].map({
    "No": 0,
    "Yes": 1
})


print("\nTarget distribution:")
print(y_9_11.value_counts())


# ------------------------------------------------------------
# 9. Train-test split
# ------------------------------------------------------------

X_train_9_11, X_test_9_11, y_train_9_11, y_test_9_11 = train_test_split(
    X_9_11,
    y_9_11,
    test_size=0.20,
    random_state=42,
    stratify=y_9_11
)


print("\nTraining data:", X_train_9_11.shape)
print("Testing data:", X_test_9_11.shape)


# ------------------------------------------------------------
# 10. Categorical and numerical columns
# ------------------------------------------------------------

categorical_features_9_11 = [
    "Gender",
    "Nativelang",
    "Otherlang"
]

numerical_features_9_11 = [
    col
    for col in X_9_11.columns
    if col not in categorical_features_9_11
]


# ------------------------------------------------------------
# 11. Preprocessing
# ------------------------------------------------------------

preprocessor_9_11 = ColumnTransformer([
    
    (
        "categorical",
        OneHotEncoder(
            drop="first",
            handle_unknown="ignore"
        ),
        categorical_features_9_11
    ),
    
    (
        "numerical",
        "passthrough",
        numerical_features_9_11
    )
])


# ------------------------------------------------------------
# 12. Handle class imbalance
# ------------------------------------------------------------

scale_pos_weight_9_11 = (
    (y_train_9_11 == 0).sum()
    /
    (y_train_9_11 == 1).sum()
)


print(
    "\nScale positive weight:",
    scale_pos_weight_9_11
)


# ------------------------------------------------------------
# 13. XGBoost model
# ------------------------------------------------------------

xgb_9_11 = XGBClassifier(
    
    n_estimators=200,
    max_depth=6,
    learning_rate=0.05,
    
    subsample=0.8,
    colsample_bytree=0.8,
    
    scale_pos_weight=scale_pos_weight_9_11,
    
    random_state=42,
    
    eval_metric="logloss"
)


# ------------------------------------------------------------
# 14. Complete pipeline
# ------------------------------------------------------------

pipeline_9_11 = Pipeline([
    
    (
        "preprocessing",
        preprocessor_9_11
    ),
    
    (
        "xgboost",
        xgb_9_11
    )
])


# ------------------------------------------------------------
# 15. Train model
# ------------------------------------------------------------

pipeline_9_11.fit(
    X_train_9_11,
    y_train_9_11
)


print("\n✅ 9–11 XGBoost model trained successfully!")


# ============================================================
# MODEL 3 — AGE 12–17
# ============================================================

print("\n====================================")
print("TRAINING MODEL FOR AGE 12–17")
print("====================================")


# ------------------------------------------------------------
# 16. Separate X and y
# ------------------------------------------------------------

X_12_17 = df_12_17.drop("Dyslexia", axis=1)

y_12_17 = df_12_17["Dyslexia"].map({
    "No": 0,
    "Yes": 1
})


print("\nTarget distribution:")
print(y_12_17.value_counts())


# ------------------------------------------------------------
# 17. Train-test split
# ------------------------------------------------------------

X_train_12_17, X_test_12_17, y_train_12_17, y_test_12_17 = train_test_split(
    X_12_17,
    y_12_17,
    test_size=0.20,
    random_state=42,
    stratify=y_12_17
)


print("\nTraining data:", X_train_12_17.shape)
print("Testing data:", X_test_12_17.shape)


# ------------------------------------------------------------
# 18. Categorical and numerical columns
# ------------------------------------------------------------

categorical_features_12_17 = [
    "Gender",
    "Nativelang",
    "Otherlang"
]

numerical_features_12_17 = [
    col
    for col in X_12_17.columns
    if col not in categorical_features_12_17
]


# ------------------------------------------------------------
# 19. Preprocessing
# ------------------------------------------------------------

preprocessor_12_17 = ColumnTransformer([
    
    (
        "categorical",
        OneHotEncoder(
            drop="first",
            handle_unknown="ignore"
        ),
        categorical_features_12_17
    ),
    
    (
        "numerical",
        "passthrough",
        numerical_features_12_17
    )
])


# ------------------------------------------------------------
# 20. Handle class imbalance
# ------------------------------------------------------------

scale_pos_weight_12_17 = (
    (y_train_12_17 == 0).sum()
    /
    (y_train_12_17 == 1).sum()
)


print(
    "\nScale positive weight:",
    scale_pos_weight_12_17
)


# ------------------------------------------------------------
# 21. XGBoost model
# ------------------------------------------------------------

xgb_12_17 = XGBClassifier(
    
    n_estimators=200,
    max_depth=6,
    learning_rate=0.05,
    
    subsample=0.8,
    colsample_bytree=0.8,
    
    scale_pos_weight=scale_pos_weight_12_17,
    
    random_state=42,
    
    eval_metric="logloss"
)


# ------------------------------------------------------------
# 22. Complete pipeline
# ------------------------------------------------------------

pipeline_12_17 = Pipeline([
    
    (
        "preprocessing",
        preprocessor_12_17
    ),
    
    (
        "xgboost",
        xgb_12_17
    )
])


# ------------------------------------------------------------
# 23. Train model
# ------------------------------------------------------------

pipeline_12_17.fit(
    X_train_12_17,
    y_train_12_17
)


print("\n✅ 12–17 XGBoost model trained successfully!")


# ============================================================
# FINAL CHECK
# ============================================================

print("\n====================================")
print("ALL THREE MODELS")
print("====================================")

print("✅ 7–8 model  : pipeline_7_8")
print("✅ 9–11 model : pipeline_9_11")
print("✅ 12–17 model: pipeline_12_17")

9–11 features: 166
12–17 features: 190

9–11 dataset shape: (380, 167)
12–17 dataset shape: (834, 191)

====================================
TRAINING MODEL FOR AGE 9–11
====================================

Target distribution:
Dyslexia
0    345
1     35
Name: count, dtype: int64

Training data: (304, 166)
Testing data: (76, 166)

Scale positive weight: 9.857142857142858

✅ 9–11 XGBoost model trained successfully!

====================================
TRAINING MODEL FOR AGE 12–17
====================================

Target distribution:
Dyslexia
0    757
1     77
Name: count, dtype: int64

Training data: (667, 190)
Testing data: (167, 190)

Scale positive weight: 9.758064516129032

✅ 12–17 XGBoost model trained successfully!

====================================
ALL THREE MODELS
====================================
✅ 7–8 model  : pipeline_7_8
✅ 9–11 model : pipeline_9_11
✅ 12–17 model: pipeline_12_17

In [17]:
# ============================================================
# EVALUATE ALL 3 XGBOOST MODELS
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)


# ------------------------------------------------------------
# FUNCTION TO EVALUATE A MODEL
# ------------------------------------------------------------

def evaluate_model(model, X_test, y_test, model_name):

    # Prediction probabilities
    y_probability = model.predict_proba(X_test)[:, 1]

    # Default threshold = 0.50 for initial evaluation
    y_prediction = (y_probability >= 0.50).astype(int)

    accuracy = accuracy_score(y_test, y_prediction)
    precision = precision_score(
        y_test,
        y_prediction,
        zero_division=0
    )
    recall = recall_score(
        y_test,
        y_prediction,
        zero_division=0
    )
    f1 = f1_score(
        y_test,
        y_prediction,
        zero_division=0
    )
    auc = roc_auc_score(
        y_test,
        y_probability
    )

    print("\n========================================")
    print(model_name)
    print("========================================")

    print(f"Accuracy  : {accuracy:.4f} ({accuracy*100:.2f}%)")
    print(f"Precision : {precision:.4f} ({precision*100:.2f}%)")
    print(f"Recall    : {recall:.4f} ({recall*100:.2f}%)")
    print(f"F1 Score  : {f1:.4f}")
    print(f"ROC-AUC   : {auc:.4f}")

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_prediction))

    print("\nClassification Report:")
    print(
        classification_report(
            y_test,
            y_prediction,
            target_names=["No Dyslexia", "Dyslexia"],
            zero_division=0
        )
    )

    return {
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1,
        "ROC-AUC": auc
    }


# ============================================================
# 7–8 MODEL
# ============================================================

results_7_8 = evaluate_model(
    pipeline_7_8,
    X_test_7_8,
    y_test_7_8,
    "XGBoost — Age 7–8"
)


# ============================================================
# 9–11 MODEL
# ============================================================

results_9_11 = evaluate_model(
    pipeline_9_11,
    X_test_9_11,
    y_test_9_11,
    "XGBoost — Age 9–11"
)


# ============================================================
# 12–17 MODEL
# ============================================================

results_12_17 = evaluate_model(
    pipeline_12_17,
    X_test_12_17,
    y_test_12_17,
    "XGBoost — Age 12–17"
)

========================================
XGBoost — Age 7–8
========================================
Accuracy  : 0.9828 (98.28%)
Precision : 1.0000 (100.00%)
Recall    : 0.8333 (83.33%)
F1 Score  : 0.9091
ROC-AUC   : 0.9968

Confusion Matrix:
[[52  0]
 [ 1  5]]

Classification Report:
              precision    recall  f1-score   support

 No Dyslexia       0.98      1.00      0.99        52
    Dyslexia       1.00      0.83      0.91         6

    accuracy                           0.98        58
   macro avg       0.99      0.92      0.95        58
weighted avg       0.98      0.98      0.98        58


========================================
XGBoost — Age 9–11
========================================
Accuracy  : 0.9605 (96.05%)
Precision : 1.0000 (100.00%)
Recall    : 0.5714 (57.14%)
F1 Score  : 0.7273
ROC-AUC   : 1.0000

Confusion Matrix:
[[69  0]
 [ 3  4]]

Classification Report:
              precision    recall  f1-score   support

 No Dyslexia       0.96      1.00      0.98        69
    Dyslexia       1.00      0.57      0.73         7

    accuracy                           0.96        76
   macro avg       0.98      0.79      0.85        76
weighted avg       0.96      0.96      0.96        76


========================================
XGBoost — Age 12–17
========================================
Accuracy  : 0.9940 (99.40%)
Precision : 1.0000 (100.00%)
Recall    : 0.9333 (93.33%)
F1 Score  : 0.9655
ROC-AUC   : 1.0000

Confusion Matrix:
[[152   0]
 [  1  14]]

Classification Report:
              precision    recall  f1-score   support

 No Dyslexia       0.99      1.00      1.00       152
    Dyslexia       1.00      0.93      0.97        15

    accuracy                           0.99       167
   macro avg       1.00      0.97      0.98       167
weighted avg       0.99      0.99      0.99       167

In [18]:
results_df = pd.DataFrame([
    results_7_8,
    results_9_11,
    results_12_17
])

display(results_df)

                 Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC
0    XGBoost — Age 7–8  0.982759        1.0  0.833333  0.909091  0.996795
1   XGBoost — Age 9–11  0.960526        1.0  0.571429  0.727273  1.000000
2  XGBoost — Age 12–17  0.994012        1.0  0.933333  0.965517  1.000000

In [20]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


def threshold_analysis(model, X_test, y_test, model_name):

    probabilities = model.predict_proba(X_test)[:, 1]

    results = []

    thresholds = np.arange(0.10, 0.55, 0.05)

    for threshold in thresholds:

        predictions = (
            probabilities >= threshold
        ).astype(int)

        results.append({
            "Threshold": round(threshold, 2),
            "Accuracy": accuracy_score(
                y_test, predictions
            ),
            "Precision": precision_score(
                y_test,
                predictions,
                zero_division=0
            ),
            "Recall": recall_score(
                y_test,
                predictions,
                zero_division=0
            ),
            "F1 Score": f1_score(
                y_test,
                predictions,
                zero_division=0
            )
        })

    result_df = pd.DataFrame(results)

    print("\n===================================")
    print(model_name)
    print("===================================")

    display(result_df)

    return result_df
threshold_7_8 = threshold_analysis(
    pipeline_7_8,
    X_test_7_8,
    y_test_7_8,
    "Age 7–8"
)

threshold_9_11 = threshold_analysis(
    pipeline_9_11,
    X_test_9_11,
    y_test_9_11,
    "Age 9–11"
)

threshold_12_17 = threshold_analysis(
    pipeline_12_17,
    X_test_12_17,
    y_test_12_17,
    "Age 12–17"
)

===================================
Age 7–8
===================================

   Threshold  Accuracy  Precision    Recall  F1 Score
0       0.10  0.982759   0.857143  1.000000  0.923077
1       0.15  0.982759   0.857143  1.000000  0.923077
2       0.20  0.965517   0.833333  0.833333  0.833333
3       0.25  0.965517   0.833333  0.833333  0.833333
4       0.30  0.965517   0.833333  0.833333  0.833333
5       0.35  0.965517   0.833333  0.833333  0.833333
6       0.40  0.982759   1.000000  0.833333  0.909091
7       0.45  0.982759   1.000000  0.833333  0.909091
8       0.50  0.982759   1.000000  0.833333  0.909091

===================================
Age 9–11
===================================

   Threshold  Accuracy  Precision    Recall  F1 Score
0       0.10  1.000000        1.0  1.000000  1.000000
1       0.15  0.986842        1.0  0.857143  0.923077
2       0.20  0.986842        1.0  0.857143  0.923077
3       0.25  0.973684        1.0  0.714286  0.833333
4       0.30  0.973684        1.0  0.714286  0.833333
5       0.35  0.973684        1.0  0.714286  0.833333
6       0.40  0.973684        1.0  0.714286  0.833333
7       0.45  0.960526        1.0  0.571429  0.727273
8       0.50  0.960526        1.0  0.571429  0.727273

===================================
Age 12–17
===================================

   Threshold  Accuracy  Precision    Recall  F1 Score
0       0.10  0.994012     0.9375  1.000000  0.967742
1       0.15  1.000000     1.0000  1.000000  1.000000
2       0.20  1.000000     1.0000  1.000000  1.000000
3       0.25  1.000000     1.0000  1.000000  1.000000
4       0.30  1.000000     1.0000  1.000000  1.000000
5       0.35  1.000000     1.0000  1.000000  1.000000
6       0.40  1.000000     1.0000  1.000000  1.000000
7       0.45  1.000000     1.0000  1.000000  1.000000
8       0.50  0.994012     1.0000  0.933333  0.965517

In [21]:
import joblib

# ============================================================
# SAVE THE THREE XGBOOST MODELS
# ============================================================

models_package = {
    
    "age_7_8": {
        "model": pipeline_7_8,
        "features": features_7_8,
        "threshold": 0.15
    },
    
    "age_9_11": {
        "model": pipeline_9_11,
        "features": features_9_11,
        "threshold": 0.15
    },
    
    "age_12_17": {
        "model": pipeline_12_17,
        "features": features_12_17,
        "threshold": 0.15
    }
}


joblib.dump(
    models_package,
    "dyslexia_age_specific_xgboost_models.pkl"
)

print("✅ All three models saved successfully!")

✅ All three models saved successfully!

In [22]:
# ============================================================
# ENGLISH QUESTION BANK FOR THE GAMIFIED TEST
# ============================================================

questions = {

    1: {
        "task": "Letter Recognition",
        "instruction": "Select the letter that matches the target letter.",
        "skill": "Letter recognition"
    },

    2: {
        "task": "Letter Recognition",
        "instruction": "Find the same letter as the one shown above.",
        "skill": "Letter recognition"
    },

    3: {
        "task": "Letter-Sound Matching",
        "instruction": "Choose the letter that makes the given sound.",
        "skill": "Letter-sound association"
    },

    4: {
        "task": "Letter-Sound Matching",
        "instruction": "Select the letter that matches the sound you hear.",
        "skill": "Letter-sound association"
    },

    5: {
        "task": "Syllable Matching",
        "instruction": "Choose the syllable that matches the target syllable.",
        "skill": "Syllable recognition"
    },

    6: {
        "task": "Syllable Matching",
        "instruction": "Find the matching syllable.",
        "skill": "Syllable recognition"
    },

    7: {
        "task": "Syllable Matching",
        "instruction": "Select the syllable that sounds the same.",
        "skill": "Syllable recognition"
    },

    8: {
        "task": "Syllable Matching",
        "instruction": "Choose the correct matching syllable.",
        "skill": "Syllable recognition"
    },

    9: {
        "task": "Syllable Matching",
        "instruction": "Find the syllable that matches the target.",
        "skill": "Syllable recognition"
    },

    10: {
        "task": "Word Recognition",
        "instruction": "Select the word that matches the picture.",
        "skill": "Word recognition"
    },

    11: {
        "task": "Word Recognition",
        "instruction": "Choose the correctly written word.",
        "skill": "Word recognition"
    },

    12: {
        "task": "Word Recognition",
        "instruction": "Find the word that you hear.",
        "skill": "Word recognition"
    },

    13: {
        "task": "Word Recognition",
        "instruction": "Select the correct word from the options.",
        "skill": "Word recognition"
    },

    14: {
        "task": "Visual Search",
        "instruction": "Find the target letter among the other letters.",
        "skill": "Visual attention"
    },

    15: {
        "task": "Visual Search",
        "instruction": "Find the target symbol as quickly as possible.",
        "skill": "Visual attention"
    },

    16: {
        "task": "Visual Search",
        "instruction": "Select the matching item from the group.",
        "skill": "Visual attention"
    },

    17: {
        "task": "Visual Search",
        "instruction": "Find the target among the displayed items.",
        "skill": "Visual attention"
    },

    18: {
        "task": "Word-Pseudoword Discrimination",
        "instruction": "Choose the item that is a real English word.",
        "skill": "Word discrimination"
    },

    19: {
        "task": "Word-Pseudoword Discrimination",
        "instruction": "Identify the real word.",
        "skill": "Word discrimination"
    },

    20: {
        "task": "Word-Pseudoword Discrimination",
        "instruction": "Select the correctly formed English word.",
        "skill": "Word discrimination"
    },

    21: {
        "task": "Word-Pseudoword Discrimination",
        "instruction": "Choose the word that exists in English.",
        "skill": "Word discrimination"
    },

    22: {
        "task": "Missing Letter",
        "instruction": "Choose the missing letter to complete the word.",
        "skill": "Spelling"
    },

    23: {
        "task": "Extra Letter",
        "instruction": "Find the extra letter in the word.",
        "skill": "Spelling"
    },

    24: {
        "task": "Semantic Error",
        "instruction": "Choose the sentence with the correct meaning.",
        "skill": "Language comprehension"
    },

    25: {
        "task": "Syntactic Error",
        "instruction": "Choose the sentence that is grammatically correct.",
        "skill": "Grammar"
    },

    26: {
        "task": "Spelling Correction",
        "instruction": "Select the correctly spelled word.",
        "skill": "Spelling"
    },

    27: {
        "task": "Letter Rearrangement",
        "instruction": "Arrange the letters to form a correct word.",
        "skill": "Spelling and sequencing"
    },

    28: {
        "task": "Syllable Rearrangement",
        "instruction": "Arrange the syllables to form a correct word.",
        "skill": "Sequencing"
    },

    29: {
        "task": "Word Separation",
        "instruction": "Separate the words correctly.",
        "skill": "Word segmentation"
    },

    30: {
        "task": "Visual Working Memory",
        "instruction": "Remember the displayed items and select them in the correct order.",
        "skill": "Working memory"
    },

    31: {
        "task": "Sentence Interaction",
        "instruction": "Read the sentence and select the correct response.",
        "skill": "Language processing"
    },

    32: {
        "task": "Auditory Working Memory",
        "instruction": "Listen carefully and select the items in the order you heard them.",
        "skill": "Auditory working memory"
    }
}


print("Total questions:", len(questions))

Total questions: 32

In [23]:
for q, details in questions.items():

    print(
        f"Q{q}: "
        f"{details['task']} → "
        f"{details['instruction']}"
    )

Q1: Letter Recognition → Select the letter that matches the target letter.
Q2: Letter Recognition → Find the same letter as the one shown above.
Q3: Letter-Sound Matching → Choose the letter that makes the given sound.
Q4: Letter-Sound Matching → Select the letter that matches the sound you hear.
Q5: Syllable Matching → Choose the syllable that matches the target syllable.
Q6: Syllable Matching → Find the matching syllable.
Q7: Syllable Matching → Select the syllable that sounds the same.
Q8: Syllable Matching → Choose the correct matching syllable.
Q9: Syllable Matching → Find the syllable that matches the target.
Q10: Word Recognition → Select the word that matches the picture.
Q11: Word Recognition → Choose the correctly written word.
Q12: Word Recognition → Find the word that you hear.
Q13: Word Recognition → Select the correct word from the options.
Q14: Visual Search → Find the target letter among the other letters.
Q15: Visual Search → Find the target symbol as quickly as possible.
Q16: Visual Search → Select the matching item from the group.
Q17: Visual Search → Find the target among the displayed items.
Q18: Word-Pseudoword Discrimination → Choose the item that is a real English word.
Q19: Word-Pseudoword Discrimination → Identify the real word.
Q20: Word-Pseudoword Discrimination → Select the correctly formed English word.
Q21: Word-Pseudoword Discrimination → Choose the word that exists in English.
Q22: Missing Letter → Choose the missing letter to complete the word.
Q23: Extra Letter → Find the extra letter in the word.
Q24: Semantic Error → Choose the sentence with the correct meaning.
Q25: Syntactic Error → Choose the sentence that is grammatically correct.
Q26: Spelling Correction → Select the correctly spelled word.
Q27: Letter Rearrangement → Arrange the letters to form a correct word.
Q28: Syllable Rearrangement → Arrange the syllables to form a correct word.
Q29: Word Separation → Separate the words correctly.
Q30: Visual Working Memory → Remember the displayed items and select them in the correct order.
Q31: Sentence Interaction → Read the sentence and select the correct response.
Q32: Auditory Working Memory → Listen carefully and select the items in the order you heard them.